set path="C:\Program Files\WinRAR\";%path%
WinRAR a -afzip -ep1 -ibck -r -y "addon-packed.zip" ^
-x.gitignore ^
-x*.zip ^
-x__pycache__ ^
-x*\__pycache__ ^
-x\web\node_modules ^
-x\web\src ^
-xindex ^
-x*.bat ^
-x*.txt ^
-x*.sh ^
-x*.db ^
-x*\*.db ^
-xmeta.json ^
-x\.git ^
-x\.vscode ^
-x\tests\ ^
-x\src\rs\siacrs\siacrs_venv ^
-x\src\rs\siacrs\src ^
-x\src\rs\siacrs\target ^
-x\web\package.json ^
-x\web\package-lock.json ^
-x\web\webpack.config.js ^
-x\.github\ ^